# Generated by Django 5.0.6 on 2024-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='in_progress', max_length=20),
        ),
    ]
